Build react native demo

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -867,3 +867,116 @@ workflows:
               --timeout 3m  
       artifacts:
         - "**/ios_tests.zip"
+
+  react-native-demo-android:
+      name: React Native Demo Android
+      working_directory: react-native/react-native-demo-project
+      max_build_duration: 120
+      instance_type: mac_mini_m2
+      environment:
+        android_signing:
+          - codemagic_keystore
+        groups:
+          - google_credentials # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
+        vars:
+          PACKAGE_NAME: "io.codemagic.cmflutteryaml" # <-- Put your package name here e.g. com.domain.myapp
+        node: v22.13.1
+      scripts:
+          - name: Install npm dependencies
+            script: |
+              npm install
+          - name: Set Android SDK location
+            script: |
+              echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"            
+          - name: Build Android release
+            script: |
+              LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+              if [ -z "$LATEST_GOOGLE_PLAY_BUILD_NUMBER" ]; then
+                # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+              else
+                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+              fi
+              cd android
+              ./gradlew bundleRelease \
+                -PversionCode=$UPDATED_BUILD_NUMBER \
+                -PversionName=1.0.$UPDATED_BUILD_NUMBER
+      artifacts:
+          - android/app/build/outputs/**/*.aab
+      publishing:
+        email:
+          recipients:
+            - user_1@example.com
+            - user_2@example.com
+          notify:
+            success: true     # To not receive a notification when a build succeeds
+            failure: false    # To not receive a notification when a build fails
+        google_play:
+          credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+          track: alpha   # Any default or custom track that is not in ‘draft’ status
+  
+  react-native-demo-ios:
+      name: React Native Demo iOS
+      working_directory: react-native/react-native-demo-project
+      max_build_duration: 120
+      instance_type: mac_mini_m2
+      integrations:
+        app_store_connect: codemagic
+      environment:
+        ios_signing:
+          distribution_type: app_store
+          bundle_identifier: io.codemagic.cmflutteryaml
+        vars:
+          XCODE_WORKSPACE: "CodemagicSample.xcworkspace" # <-- Put the name of your Xcode workspace here
+          XCODE_SCHEME: "CodemagicSample" # <-- Put the name of your Xcode scheme here
+          APP_ID: 1555555551 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
+        node: v22.13.1
+        xcode: latest
+        cocoapods: default
+      scripts:
+          - name: Install npm dependencies
+            script: |
+              npm install
+          - name: Install CocoaPods dependencies
+            script: |
+              cd ios && pod install
+          - name: Set up code signing settings on Xcode project
+            script: |
+              xcode-project use-profiles --warn-only
+          - name: Increment build number
+            script: |
+              # Information about getting the latest build version can be found here: https://docs.codemagic.io/knowledge-codemagic/build-versioning/#app-store-or-testflight-latest-build-number
+              cd $CM_BUILD_DIR/ios
+              LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_ID")
+              agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
+          - name: Build ipa for distribution
+            script: |
+              xcode-project build-ipa \
+                --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
+                --scheme "$XCODE_SCHEME"
+      artifacts:
+          - build/ios/ipa/*.ipa
+          - /tmp/xcodebuild_logs/*.log
+          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
+          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
+      publishing:
+        email:
+          recipients:
+            - user_1@example.com
+            - user_2@example.com
+          notify:
+            success: true
+            failure: false
+        app_store_connect:
+          auth: integration
+
+          # Configuration related to TestFlight (optional)
+          # Note: This action is performed during post-processing.
+          submit_to_testflight: true
+          beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
+            - group name 1
+            - group name 2
+
+          # Configuration related to App Store (optional)
+          # Note: This action is performed during post-processing.
+          submit_to_app_store: false
