Update codemagic.yaml

diff --git a/ionic/ionic-capacitor-demo-project/codemagic.yaml b/ionic/ionic-capacitor-demo-project/codemagic.yaml
--- a/ionic/ionic-capacitor-demo-project/codemagic.yaml
+++ b/ionic/ionic-capacitor-demo-project/codemagic.yaml
@@ -77,66 +77,66 @@ workflows:
         submit_to_app_store: false
 
 
-  ionic-capacitor-android-workflow:
-    name: Ionic Capacitor Android Workflow
-    max_build_duration: 120
-    instance_type: mac_mini_m1
-    environment:
-      android_signing:
-        - keystore_reference
-      groups:
-        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put CONTENTS of your Gloud crendentials file here)
-      vars:
-        PACKAGE_NAME: "io.codemagic.ionicsample"
-        GOOGLE_PLAY_TRACK: alpha
-      node: latest
-    triggering:
-      events:
-        - push
-        - tag
-        - pull_request
-      branch_patterns:
-        - pattern: develop
-          include: true
-          source: true
-    scripts:
-      - name: Install npm dependencies for Ionic project
-        script: |
-          npm install
-      - name: Set Android SDK location
-        script: |
-          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
-      - name: Update dependencies and copy web assets to native project
-        script: |
-          # npx cap copy # <- use this is you don't need to update native dependencies
-          npx cap sync # <- update native dependencies and copy web assets to native project
-      - name: Build Android release
-        script: |
-          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-          if [ -z LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
-            # fallback in case no build number was found from Google Play.
-            # Alternatively, you can `exit 1` to fail the build
-            # BUILD_NUMBER is a Codemagic built-in variable tracking the number
-            # of times this workflow has been built
-            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-          else
-            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-          fi
-          cd $CM_BUILD_DIR/android
-          ./gradlew bundleRelease \
-            -PversionCode=$UPDATED_BUILD_NUMBER \
-            -PversionName=1.0.$UPDATED_BUILD_NUMBER
-    artifacts:
-      - android/app/build/outputs/**/*.apk
-    publishing:
-      email:
-        recipients:
-          - user_1@example.com
-          - user_2@example.com
-        notify:
-          success: true
-          failure: false
-      google_play:
-        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
-        track: internal
-        submit_as_draft: true
+  # ionic-capacitor-android-workflow:
+  #   name: Ionic Capacitor Android Workflow
+  #   max_build_duration: 120
+  #   instance_type: mac_mini_m1
+  #   environment:
+  #     android_signing:
+  #       - keystore_reference
+  #     groups:
+  #       - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put CONTENTS of your Gloud crendentials file here)
+  #     vars:
+  #       PACKAGE_NAME: "io.codemagic.ionicsample"
+  #       GOOGLE_PLAY_TRACK: alpha
+  #     node: latest
+  #   triggering:
+  #     events:
+  #       - push
+  #       - tag
+  #       - pull_request
+  #     branch_patterns:
+  #       - pattern: develop
+  #         include: true
+  #         source: true
+  #   scripts:
+  #     - name: Install npm dependencies for Ionic project
+  #       script: |
+  #         npm install
+  #     - name: Set Android SDK location
+  #       script: |
+  #         echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
+  #     - name: Update dependencies and copy web assets to native project
+  #       script: |
+  #         # npx cap copy # <- use this is you don't need to update native dependencies
+  #         npx cap sync # <- update native dependencies and copy web assets to native project
+  #     - name: Build Android release
+  #       script: |
+  #         LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+  #         if [ -z LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+  #           # fallback in case no build number was found from Google Play.
+  #           # Alternatively, you can `exit 1` to fail the build
+  #           # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+  #           # of times this workflow has been built
+  #           UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+  #         else
+  #           UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+  #         fi
+  #         cd $CM_BUILD_DIR/android
+  #         ./gradlew bundleRelease \
+  #           -PversionCode=$UPDATED_BUILD_NUMBER \
+  #           -PversionName=1.0.$UPDATED_BUILD_NUMBER
+  #   artifacts:
+  #     - android/app/build/outputs/**/*.apk
+  #   publishing:
+  #     email:
+  #       recipients:
+  #         - user_1@example.com
+  #         - user_2@example.com
+  #       notify:
+  #         success: true
+  #         failure: false
+  #     google_play:
+  #       credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+  #       track: internal
+  #       submit_as_draft: true
